name: Update Image

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 4"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get n8n version
        id: n8n_version
        run: |
          # Pull the latest n8n image to get its version
          docker pull docker.n8n.io/n8nio/n8n:latest

          # Extract the n8n version from the image
          N8N_VERSION=$(docker run --rm docker.n8n.io/n8nio/n8n:latest n8n --version)
          echo "N8N version: $N8N_VERSION"

          # Extract major, minor, and patch version
          MAJOR_VERSION=$(echo $N8N_VERSION | cut -d. -f1)
          MINOR_VERSION=$(echo $N8N_VERSION | cut -d. -f2)
          PATCH_VERSION=$(echo $N8N_VERSION | cut -d. -f3)

          # Set output variables
          echo "version=$N8N_VERSION" >> $GITHUB_OUTPUT
          echo "major=$MAJOR_VERSION" >> $GITHUB_OUTPUT
          echo "minor=$MINOR_VERSION" >> $GITHUB_OUTPUT
          echo "patch=$PATCH_VERSION" >> $GITHUB_OUTPUT

          # Generate tag list
          TAGS="synthropai/synthrop-n8n:latest,synthropai/synthrop-n8n:$MAJOR_VERSION,synthropai/synthrop-n8n:$MAJOR_VERSION.$MINOR_VERSION,synthropai/synthrop-n8n:$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.n8n_version.outputs.tags }}
